Fix typos
Signed-off-by: Andrea Gelmini <andrea.gelmini@gelma.net>

diff --git a/tests/imsm-grow-template b/tests/imsm-grow-template
--- a/tests/imsm-grow-template
+++ b/tests/imsm-grow-template
@@ -25,7 +25,7 @@ function grow_member() {
 	local status=$?
 	if [ $negative_test -ne 0 ]; then
 		if [ $status -eq 0 ]; then
-			echo >&2 "**Error**: $member: --grow should failed, but it completed successfuly"
+			echo >&2 "**Error**: $member: --grow should failed, but it completed successfully"
 			exit 1
 		fi
 		return
@@ -99,7 +99,7 @@ else
 	grow_status=$?
 	if [ $negative_test -ne 0 ]; then
 		if [ $grow_status -eq 0 ]; then
-			echo >&2 "**Error**: $container: --grow should failed, but it completed successfuly"
+			echo >&2 "**Error**: $container: --grow should failed, but it completed successfully"
 			exit 1
 		fi
 	else
